#pragma once
#include <string>
#include <vector>
std::vector<std::string> palette_last_place={
"sand",
"gravel",
"golden_rail",
"tallgrass",
"deadbush",
  "yellow_flower",
  "red_flower",
  "brown_mushroom",
  "red_mushroom",
  "torch",
  "fire",
  "wheat",
  "wooden_door",
  "ladder",
  "rail",
  "iron_door",
  "acacia_door",
  "acacia_trapdoor",
  "birch_door",
  "birch_trapdoor",
  "dark_oak_door",
  "dark_oak_trapdoor",
  "iron_trapdoor",
  "jungle_door",
  "jungle_trapdoor",
  "spruce_door",
  "spruce_trapdoor",
  "snow_layer",
  "cactus",
  "reeds",
  "trapdoor",
  "pumpkin_stem",
  "melon_stem",
  "vines",
  "waterlily",
  "cocoa",
  "carrots",
  "potatoes",
  "double_plant",
  "cyan_glazed_tarracotta"};
