name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        git submodule init
        git submodule checkout
    - name: make
      run: make static
 
