name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: |
        sudo apt install cxxtest libuv-dev
        git submodule init
        git submodule update
        cd uWebSockets
        git submodule init
        git submodule update
        cd ..
    - name: make
      run: make static
 
